### ISSUE TITLE
I have different hash for Mavericks 10.9.5 (13F34)

### ISSUE THREAD

**Issue by LukasAppleFan** [notpeter/apple-installer-checksums#118]
Hello,
I have hash ba6e42ad05fd002c368f2e37f026b2781c87439e for OS X Mavericks 10.9.5 (13F34)
I can confirm it exists as I was able to find it on an old Japanese website.

**Comment by MrHallway0** [comment]
I added my hash to line 120 or 119, it would appear that not all of Apple's Mac OS hashes where added, you will also need to make sure that you have an *official* and *legit* `.dmg` by your self.

**Comment by LukasAppleFan** [comment]
How can I tell whether or not my DMG is legit ? I can at least confirm that installing from USB on my MacBook Pro worked no problem

**Comment by BetaPictoris** [comment]
> How can I tell whether or not my DMG is legit ? I can at least confirm that installing from USB on my MacBook Pro worked no problem

If you installed it, and everything seems legit, then it is probably legit. If you downloaded it from Apple.com then it is probably legit as well.
