### ISSUE TITLE
missing snow leapord 10.6.8

### ISSUE THREAD

**Issue by jredfox** [notpeter/apple-installer-checksums#123]
my favorite version of mac is not there and I want to download it then have a valid file but, I can't without a checksum. everyone sees mac and remembers that version.

**Comment by notpeter** [comment]
Snow Leopard discs are actually kinda rare, most retail discs were 10.6.0 or 10.6.3 and >= 10.6.6 was primarily distributed via the app store.  It's been a long time, but I believe back in the day I had a 10.6.8 retail disc (acquired directly via Apple GSX) so I think it's possible there are disc/images out there.  

Pull Requests accepted!

**Comment by jredfox** [comment]
I don't have a pull request in a matter of fact if you have the actual files why don't you dm me the dmg file or the iso file depending on how you ripped the files off of the disk
