### ISSUE TITLE
macOS Big Sur 11.6 (20G165) checksum

### ISSUE THREAD

**Issue by syouko** [notpeter/apple-installer-checksums#137]
~ % shasum /Applications/Install\ macOS\ Big\ Sur.app/Contents/SharedSupport/SharedSupport.dmg

**2e89d67ebb02d1c655dfb875144e2c15bd6fa726**  /Applications/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg

~ % sw_vers
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

That's my result
Hope can provide some help :P

**Comment by sapperlott** [comment]
I can confirm that SHA1 hash - same here.

**Comment by markmentovai** [comment]
Thanks! We already have #135 for this, but we can treat this as confirmation.

Duplicate of #135

**Comment by markmentovai** [comment]
Duplciate of #135

**Comment by markmentovai** [comment]
Duplicate of #135
