### ISSUE TITLE
Add checksum for Monterey 12.6.3

### ISSUE THREAD

**Issue by FonzTech** [notpeter/apple-installer-checksums#150]
Checksum for macOS Monterey 12.6.3's `SharedSupport.dmg` is `43fd6b9d10021de7ae7430db9fbafa70d3d5c8d1`.

**Comment by LOVEFIR3** [comment]
> Checksum for macOS Monterey 12.6.3's `SharedSupport.dmg` is `43fd6b9d10021de7ae7430db9fbafa70d3d5c8d1`.

I got something different for 12.6 `SharedSupport.dmg` is `be965248f8e1b6c2c110aa1445ae4db912f676cd`.

**Comment by FonzTech** [comment]
> > Checksum for macOS Monterey 12.6.3's `SharedSupport.dmg` is `43fd6b9d10021de7ae7430db9fbafa70d3d5c8d1`.
> 
> I got something different for 12.6 `SharedSupport.dmg` is `be965248f8e1b6c2c110aa1445ae4db912f676cd`.

What version are you talking about? I am talking about `12.6.3`, NOT `12.6` !
