### ISSUE TITLE
Verify Checksums for OS X installer name change for Terminal command

### ISSUE THREAD

**Issue by ktilford** [notpeter/apple-installer-checksums#16]
In the "Verify Checksums" for OS X the given Terminal command "shasum /Applications/Install\ OS\ X\ *.app/Contents/SharedSupport/InstallESD.dmg" does not work for Sierra installers because the installer name changed from "OS X" to "macOS" so the new command for Sierra should be "shasum /Applications/Install\ macOS\ Sierra.app/Contents/SharedSupport/InstallESD.dmg".

**Comment by notpeter** [comment]
Thanks for the heads up.
