### ISSUE TITLE
Multiple 10.8.5 Mountain Lion builds/hashes, missing 12F37

### ISSUE THREAD

**Issue by hipunk** [notpeter/apple-installer-checksums#18]
Hello,

I had to redownload Mountain Lion from shady websites because Apple doesn't want me to download it, heck, even downloading 10.11 is a pain the ass nowadays already.

And when I checksum the InstallESD from it, I get the following result:
2919b519142e2119197bffd678f15f603e84970f

At first I thought my download was broken, so rechecked but came to the same result. Tried another download from somewhere else, same result.
So I searched Google.de for another source and I found that my InstallESD does seem to have a correct(?) shasum:
https://geekinguncovered.wordpress.com/2015/11/26/mac-os-x-install-image-hashes/
I quote:

> Mountain Lion 10.8.5 (12F37) (InstallESD.dmg)
> SHA-1: 2919B519142E2119197BFFD678F15F603E84970F
> MD5: 2C77151BE45C820B02A9ACE05434693D
> CRC-32: A9DCAE18
> 
> Mountain Lion 10.8.5 (12F37) (OS X Mountain Lion 10.8.5 Build 12F37.dmg)
> SHA-1: ECF68C2119C71825839D2A58E0D619E9CCF7C026
> MD5: 5568B4DDE00A64F765EF00858B538078
> CRC-32: F4DFCE4D

So where is the sum from we have here? (7bc54f504aa0b769a2d0b8546393a6e0fc24671f).

That is 3 different shasums for one version!?
Which one is correct?

The rest of the sums here always matched mine (10.11.3, 10.11.6 and 10.12.3), can't complain on that end. Thanks!

Greetings,

hipunk

**Comment by dodekeract** [comment]
That's odd. Might be a good idea to include a `source` link.

**Comment by hipunk** [comment]
I can't. It's from filesharing/pirating sites...

**Comment by dodekeract** [comment]
No no, I mean in the README.

**Comment by hipunk** [comment]
Oh, I see! Yes, that might be a good idea.
Additionally, we could add "12F37", because that seems to be the identifier of 10.8.5 anyway.

**Comment by hipunk** [comment]
Alright it's been a few days and we haven't got any other evidence that the 10.8.5 sha1 in the readme.md is correct.

I found this github page because it was linked on other websites, I'm sure other people did (and still do) as well. The incorrect shasum should be removed until we are certain which one is the correct one.
7bc54f504aa0b769a2d0b8546393a6e0fc24671f is only to be found in this particular readme.md, nowhere else - the other ones I posted are to be found on other websites as well. This strongly implies that the shasum here is incorrect.

10.8 is the last version of Mac OS X to have the old way of memory management, that shasum is one of the most important shasums in the list, because developers might need it for testing purposes.

This issue might have been wasting other peoples bandwidth and time as well. There's no need for it to happen again for no reason at all, so please somebody remove it.

**Comment by notpeter** [comment]
Well isn't this fun.  Apple continues to silently push revisions via the App Store to OSX installers. 12F37 is a build identifier, there are multiple build numbers which are all 10.8.5. I'm the source of the 7bc54 hash, it's legit.  But I don't have that installer handy so I can't verify the build number (InstallESD.dmg/System/Library/CoreServices/SystemVersion.plist).

I redownloaded it from the app store and got yet another 10.8.5 build (12F45), which I've added to the list.

Not sure about how to verify the authenticity of DMG in the pirated 12F37 build.  Maybe outer app file bundle is signed or some such. I'll see if I can come up with something.

**Comment by citrusui** [comment]
@notpeter, this may be the reason you are getting a different hash: https://arstechnica.com/apple/2016/03/psa-updated-apple-certificate-means-old-os-x-installers-dont-work-anymore/

I believe that Apple also bundles a copy of Install OS X|macOS.app within InstallESD.dmg, which may have changed the hash due to renewed certificates. The current installers should last until 2023.

I think it would be safe to recheck FINAL (10.7.5, 10.8.5, etc.) versions 10.7 through 10.11 to see if their hashes in the repo still match the current App Store releases (with 2023 certs)

**Comment by notpeter** [comment]
That makes perfect sense. Thanks for providing that link.
