### ISSUE TITLE
Backfill Build Numbers

### ISSUE THREAD

**Issue by notpeter** [notpeter/apple-installer-checksums#22]
In cases where there's only one build for a given version number we could backfill using Apple's published list of builds numbers:

https://support.apple.com/en-us/HT201260

**Comment by Coeur** [comment]
There are older version numbers still listed on foreign pages like https://support.apple.com/fr-fr/HT201260. As Apple may be removing those numbers with time, here is a copy:

OS X El Capitan

10.11.6	15G31
10.11.5	15F34
10.11.4	15E65
10.11.3	15D21
10.11.2	15C50
10.11.1	15B42
10.11	15A284

OS X Yosemite

10.10.5	14F27
10.10.4	14E46
10.10.3 14D136, or ? (with update)
10.10.2	14C109
10.10.1	14B25
10.10	14A389

OS X Mavericks

10.9.5	13F34
10.9.4	13E28
10.9.3	13D65
10.9.2	13C64
10.9.1	13B42
10.9	13A603

OS X Mountain Lion

10.8.5	12F37, 12F45, or 12F2029
10.8.4	12E55
10.8.3	12D78
10.8.2	12C54, 12C60, or 12C2034
10.8.1	12B19
10.8	12A269

OS X Lion

10.7.5, 11G565, or 11G63
10.7	11A511

Mac OS X Snow Leopard

10.6.8	10K540, or 10K549
10.6.3	10D575
10.6	10A432, 10A433 (Server)

Mac OS X Leopard

10.5.8	9L30, 9L34 (Server 10.5.8, version 1.1)
10.5.6	9G66
10.5	9A581

Mac OS X Tiger

10.4.11	8S165
10.4	8A428

Mac OS X Panther

10.3.9	7W98
10.3.2	7D28
10.3	7B85

Mac OS X Jaguar

10.2.8	6R65, or 6R73
10.2.3	6G37, 6G35 (Server)
10.2	6C115

Mac OS X Puma

10.1.5	5S60, 5S66 (with network update 1.0)
10.1	5G64 (5L14 or 5L17b with security update 10-19-01)

Mac OS X Cheetah

10.0	4K78

**Comment by notpeter** [comment]
PR's welcome, but verifying the correctness is very difficult for old stuff -- I'm not gonna dig up an old installer, find and old mac (or build a VM) and install just to verify the build number that matches a given media associated with the hashes we have here.

**Comment by Coeur** [comment]
4 years later. ;)
