### ISSUE TITLE
can add Xcode 9 and MacOS 10.13 beta1 SHAs?

### ISSUE THREAD

**Issue by oscarbg** [notpeter/apple-installer-checksums#24]

**Comment by markmentovai** [comment]
Yes, but the 10.13 installer has changed such that not everything is in InstallESD.dmg anymore. Notably, BaseSystem.dmg used to appear inside InstallESD.dmg, but now it’s a sibling. We may want to record both hashes.

**Comment by oscarbg** [comment]
thanks good to know..

**Comment by markmentovai** [comment]
I added the hashes for [macOS 10.13db1](c291bd015a5a5b0b5f87a221ba7f16b51a249dcb) and [Xcode 9b1](54257e6e0ad294841d6b52293790e3a473adbead).
