### ISSUE TITLE
10.4 Tiger plz

### ISSUE THREAD

**Issue by mcandre** [notpeter/apple-installer-checksums#31]
Amazon sells unopened OS X 10.4 Tiger DVD's, if some kind donator would be willing to purchase one and checksum its contents.

https://www.amazon.com/gp/offer-listing/B000BWZZLG/ref=dp_olp_new?ie=UTF8&condition=new

https://www.amazon.com/gp/offer-listing/B0007LW1MW/ref=dp_olp_new?ie=UTF8&condition=new

Or, maybe we could reach out to Apple to ask them for checksums for verifying legacy OS X installation media integrity?

**Comment by Coeur** [comment]
We should let those old OS die.
And even if one buy one of those:
* it may have been secretely repackaged, so authenticity isn't garantied
* it's dubious why one would want to authenticate an installer for an OS with plenty of unpatched security holes.

**Comment by notpeter** [comment]
Old hashes are especially important for EOL hardware, but I have no interest in asking for donations.

PRs welcome from holders of all MacOS/MacOSX discs.
