### ISSUE TITLE
10.3 Panther plz

### ISSUE THREAD

**Issue by mcandre** [notpeter/apple-installer-checksums#32]
Amazon sells unopened OS X 10.3 Panther CD-ROM's, if some kind donator would be willing to purchase one and checksum its contents.

https://www.amazon.com/gp/offer-listing/B0000E6NK9/ref=dp_olp_new?ie=UTF8&condition=new

Or, maybe we could reach out to Apple to ask them for checksums for verifying legacy OS X installation media integrity?

**Comment by notpeter** [comment]
I'm not prepared to create a wishlist of the dozens of OS releases, but PRs welcome from holders of all MacOS/MacOSX discs.
