### ISSUE TITLE
xcode 9.4 and 10.0dp1?

### ISSUE THREAD

**Issue by oscarbg** [notpeter/apple-installer-checksums#37]

**Comment by Coeur** [comment]
$ shasum Xcode_10_Beta.xip 
baf85968300b1d20421e5341976d397f580290d0  Xcode_10_Beta.xip

$ shasum Xcode_9.4.xip 
17d22ca295922a810ae69b0ae1bab7b1e3304b1d  Xcode_9.4.xip

**Comment by oscarbg** [comment]
thanks!

**Comment by notpeter** [comment]
@Coeur Would you have any interest in being added as a maintainer so you can just merge changes like this directly?

**Comment by Coeur** [comment]
@notpeter OK Peter.
