### ISSUE TITLE
Checksum High Sierra 10.13.5 (17F73)?

### ISSUE THREAD

**Issue by nsgrbr** [notpeter/apple-installer-checksums#38]
Can anyone confirm the checksum of the High Sierra 10.13.5 (17F73)?

**High Sierra 10.13.5 (17F73)**

**BaseSystem.dmg**

**shasum** /Applications/Install\ macOS\ High\ Sierra.app/Contents/SharedSupport/BaseSystem.dmg 
**a97aeffdbeda4d68e1053f69b55d9d56df4259d6**

**md5** /Applications/Install\ macOS\ High\ Sierra.app/Contents/SharedSupport/BaseSystem.dmg 
MD5 = **4057b8623b13f60654bb344a73b43358**

**InstallESD.dmg**

**shasum** /Applications/Install\ macOS\ High\ Sierra.app/Contents/SharedSupport/InstallESD.dmg 
**216b38acfb234b4e29c2dba41fd76814550b59e2**

**md5** /Applications/Install\ macOS\ High\ Sierra.app/Contents/SharedSupport/InstallESD.dmg 
MD5 = **2e49889433d173a6aa22eb9318e514aa**

cat /Applications/Install\ macOS\ High\ Sierra.app/Contents/SharedSupport/InstallInfo.plist | grep -i -A 1 version
<key>version</key>
<string>**10.13.5**</string>

cat /Applications/Install\ macOS\ High\ Sierra.app/Contents/Info.plist | grep -A 1 DTSDKBuild
<key>DTSDKBuild</key>
<string>**17F73**</string>

**Comment by notpeter** [comment]
Checksums confirmed.  In the future you can just open a PR and I or one of the other maintainers will verify and merge.  Note we also track sha256 checksums too (but hide them in comments for the moment).

Thanks for the contribution @nsgrbr!

**Comment by nsgrbr** [comment]
**Update:**

Mac OS 10.13.5 Installer - 10.13.5 (**17F73**)
/Applications/Install\ macOS\ High\ Sierra.app/Contents/Info.plist

After install Mac OS -> About This Mac -> 10.13.5 (**17F77**)
