### ISSUE TITLE
Xcode builds are listed at https://xcodereleases.com/

### ISSUE THREAD

**Issue by Coeur** [notpeter/apple-installer-checksums#43]
If one has the courage to update our hash list, we can find our missing builds at https://xcodereleases.com/

**Comment by Coeur** [comment]
Actually, they even source it on GitHub: https://github.com/xcodereleases/data

**Comment by 1alessandro1** [comment]
By now, almost if not all builds listed/linked at https://xcodereleases.com were inclued in the list, so I think this can be closed
