### ISSUE TITLE
How can I trust?

### ISSUE THREAD

**Issue by nyg** [notpeter/apple-installer-checksums#45]
Hello,

First of all, thanks for your work. My question is, how can I verify the checksums you provide? How can I know they do not come from corrupted dmg?

Many thanks,
nyg

**Comment by Coeur** [comment]
1. Simply download from apple.com for safety.
2. There is nothing official here: if you notice that your dmg has a different hash than here, then it's just a hint that either yours or ours is incorrect: which one can't be tell without re-downloading.

**Comment by nyg** [comment]
The thing is I can't download from Apple's servers, or at least I haven't found a way to ([link](https://apple.stackexchange.com/questions/309399/how-can-i-download-an-older-version-of-os-x-macos)). I'm on Mojave and I'm trying to download El Capitan but it doesn't seem to be possible because of the new App Store.

That's why I came here, thinking of downloading the installer from a torrent and verifying it with a trusted checksum.

**Comment by Coeur** [comment]
Then it's a matter of trust. If the hash has been added long time ago, then it has likely been verified by many people and is likely correct.

Note that if you're looking at it from a security point of view, then you shouldn't install an old OS to begin with. And if it's for compatibility testing purposes, then a slightly modified build may not impact the tests.

**Comment by nyg** [comment]
I've got a Mac that doesn't accept anything after El Capitan, that's why... Anyway, thanks for you help, I will close the issue.
