### ISSUE TITLE
10.14.6 hash mismatch

### ISSUE THREAD

**Issue by okrt** [notpeter/apple-installer-checksums#53]
I have downloaded latest MacOS Mojave 10.14.6 several times from Appstore and SHA1sums are not matching.
Please check:
SHA1:
7a500c36b1825c6d7e73932bf9109fd561334606  /Applications/Install macOS Mojave.app/Contents/SharedSupport/BaseSystem.dmg
6979e80dfeb28d5e7c9805afebbf3a730a94429c  /Applications/Install macOS Mojave.app/Contents/SharedSupport/InstallESD.dmg
SHA256:
ee3ff99ca59b027a6778311dc12f868b08f16c9aae948ab1e7f85a4745d39815  /Applications/Install macOS Mojave.app/Contents/SharedSupport/BaseSystem.dmg
346277cd83f7447f0e04e0d4bd9476401886d0d04132b6100455b5a8ab20f385  /Applications/Install macOS Mojave.app/Contents/SharedSupport/InstallESD.dmg

It looks like BaseSystem.dmg is signed by Apple, so either the installer updated after the release or there is another problem.

**Comment by okrt** [comment]
It looks like it is a new build 18G87, with the latest update which was released after the initial release of 10.14.6 and fixes sleep issues on some machines.
Some XML files on the build  are refering to the older build number, that's why it made me think there is an issue.
Probably this will be the final build of Mojave, so I think it is useful to add the build to the list (after your own verification, of course)
Thank you!

**Comment by mpermann** [comment]
My results match up with okrt.

$ defaults read /Applications/Install\ macOS\ Mojave.app/Contents/version.plist CFBundleShortVersionString
14.6.03

$ shasum /Applications/Install\ macOS\ Mojave.app/Contents/SharedSupport/InstallESD.dmg 
6979e80dfeb28d5e7c9805afebbf3a730a94429c  /Applications/Install macOS Mojave.app/Contents/SharedSupport/InstallESD.dmg

$ shasum /Applications/Install\ macOS\ Mojave.app/Contents/SharedSupport/BaseSystem.dmg 
7a500c36b1825c6d7e73932bf9109fd561334606  /Applications/Install macOS Mojave.app/Contents/SharedSupport/BaseSystem.dmg

**Comment by okrt** [comment]
I think installation media updated again with CFBundleShortVersionString 14.6.04
03c33e2295da173065606483d134cbda9c7f537f  /Applications/Install macOS Mojave.app/Contents/SharedSupport/BaseSystem.dmg
df554c1a284e0655ef643258ff2dddb491dc86e6  /Applications/Install macOS Mojave.app/Contents/SharedSupport/InstallESD.dmg
