### ISSUE TITLE
Does anyone know why my High Sierra downloads differ?

### ISSUE THREAD

**Issue by Saya47** [notpeter/apple-installer-checksums#63]
Hello :)
I have downloaded High Sierra twice from a same Sierra VM, the InstallESD and BaseSystem checksums look absolutely different but I've checked Info.plist and they are exactly the same.
I also downloaded HS again from my Macbook pro running El Capitan, the Info.plist is the same with above but the dmg files again look different.
I tried downloading using the dosdude1's HS patcher tool, ran it on the Sierra VM, again the dmg files absolute differ from all above.
Anyone knows the reason?

Here's the Info.plist, it's exactly the same for all the downloads I did above, (I compared checksums):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Application-Group</key>
	<string>AirPort</string>
	<key>BuildMachineOSBuild</key>
	<string>16B2657</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleDisplayName</key>
	<string>Install macOS High Sierra</string>
	<key>CFBundleExecutable</key>
	<string>InstallAssistant_springboard</string>
	<key>CFBundleGetInfoString</key>
	<string>Install macOS High Sierra, Copyright © 2007-2018 Apple Inc. All rights reserved.</string>
	<key>CFBundleIconFile</key>
	<string>InstallAssistant</string>
	<key>CFBundleIdentifier</key>
	<string>com.apple.InstallAssistant.HighSierra</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Install mac OS</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>13.6.02</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>Open Install OS X URL</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>x-install-osx-assistant</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>13602</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>9P107g</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>17G61</string>
	<key>DTSDKName</key>
	<string>macosx10.13internal</string>
	<key>DTXcode</key>
	<string>0930</string>
	<key>DTXcodeBuild</key>
	<string>9P107g</string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.utilities</string>
	<key>LSArchitecturePriority</key>
	<array>
		<string>x86_64</string>
		<string>i386</string>
		<string>ppc</string>
	</array>
	<key>LSHasLocalizedDisplayName</key>
	<true/>
	<key>LSMinimumSystemVersion</key>
	<string>10.8</string>
	<key>NSMainNibFile</key>
	<string>MainMenu</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
	<key>ProductPageIconFile</key>
	<string>ProductPageIcon.icns</string>
</dict>
</plist>

```
Note: I am downloading full installers of course, the dmg files are located at root folder: "/macOS Install Data"

**Comment by sleeve** [comment]
@Setaran Could you post the file checksums of your tests along with the specific version and build numbers? It might help narrow down what's happening.

**Comment by Setaran** [comment]
The specific version and build numbers are all the same (I have checked Info.plist files in all of them they are all the same).

0001 74e924bf7926dd1e18c6513f9b6688b0d4ec3bb4 *0001\Contents\SharedSupport\._BaseSystem.dmg
0001 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *0001\Contents\Info.plist
0001 9082686f9caabe2ffe73a8b2d3883dd6fb0fd974 *0001\Contents\SharedSupport\InstallESD.dmg
0001 cf7c315c0ee033697d8648e6d87825061b3a9cb5 *0001\Contents\SharedSupport\BaseSystem.dmg
0002 6b7522d7f78b93441ecd7dee73430af9b07b3744 *0001\Contents\SharedSupport\BaseSystem.dmg
0002 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *0001\Contents\Info.plist
0002 d7ff748612f919c9e33223300ca347da4e6b5a84 *0001\Contents\SharedSupport\InstallESDDmg.pkg
0003 13f375db7ee5e75511de2ae429530d531712bc55 *0001\Contents\SharedSupport\BaseSystem.dmg
0003 6ffeea24777521c2bd0308f1f2f94579f04a1b14 *0001\Contents\SharedSupport\InstallESDDmg.pkg
0003 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *0001\Contents\Info.plist
0004 13f375db7ee5e75511de2ae429530d531712bc55 *0001\Contents\SharedSupport\BaseSystem.dmg
0004 6ffeea24777521c2bd0308f1f2f94579f04a1b14 *0001\Contents\SharedSupport\InstallESDDmg.pkg
0004 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *0001\Contents\Info.plist

**Comment by Setaran** [comment]
@sleeve 
Download using patchet tool:
0001 74e924bf7926dd1e18c6513f9b6688b0d4ec3bb4 *\Contents\SharedSupport\._BaseSystem.dmg
0001 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist
0001 9082686f9caabe2ffe73a8b2d3883dd6fb0fd974 *\Contents\SharedSupport\InstallESD.dmg
0001 cf7c315c0ee033697d8648e6d87825061b3a9cb5 *\Contents\SharedSupport\BaseSystem.dmg
Download normally on Sierra, copying data from /macOS Install Data:
I learnt this method from here:
https://apple.stackexchange.com/a/307118/278531
0002 6b7522d7f78b93441ecd7dee73430af9b07b3744 *\Contents\SharedSupport\BaseSystem.dmg
0002 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist
0002 d7ff748612f919c9e33223300ca347da4e6b5a84 *\Contents\SharedSupport\InstallESDDmg.pkg
Second try on same machine (It's a VM machine btw):
0003 13f375db7ee5e75511de2ae429530d531712bc55 *\Contents\SharedSupport\BaseSystem.dmg
0003 6ffeea24777521c2bd0308f1f2f94579f04a1b14 *\Contents\SharedSupport\InstallESDDmg.pkg
0003 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist
Third try on Macbook Pro running El Capitan:
0004 13f375db7ee5e75511de2ae429530d531712bc55 *\Contents\SharedSupport\BaseSystem.dmg
0004 6ffeea24777521c2bd0308f1f2f94579f04a1b14 *\Contents\SharedSupport\InstallESDDmg.pkg
0004 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist

**Comment by Setaran** [comment]
@sleeve Thanks for replying to me.
Here they are:
Download using patchet tool:
0001 74e924bf7926dd1e18c6513f9b6688b0d4ec3bb4 *\Contents\SharedSupport._BaseSystem.dmg
0001 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist
0001 9082686f9caabe2ffe73a8b2d3883dd6fb0fd974 *\Contents\SharedSupport\InstallESD.dmg
0001 cf7c315c0ee033697d8648e6d87825061b3a9cb5 *\Contents\SharedSupport\BaseSystem.dmg
Download normally on Sierra, copying data from /macOS Install Data:
I learnt this method from here:
https://apple.stackexchange.com/a/307118/278531
0002 6b7522d7f78b93441ecd7dee73430af9b07b3744 *\Contents\SharedSupport\BaseSystem.dmg
0002 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist
0002 d7ff748612f919c9e33223300ca347da4e6b5a84 *\Contents\SharedSupport\InstallESDDmg.pkg
Second try on same machine (It's a VM machine btw):
0003 13f375db7ee5e75511de2ae429530d531712bc55 *\Contents\SharedSupport\BaseSystem.dmg
0003 6ffeea24777521c2bd0308f1f2f94579f04a1b14 *\Contents\SharedSupport\InstallESDDmg.pkg
0003 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist
Third try on Macbook Pro running El Capitan:
0004 13f375db7ee5e75511de2ae429530d531712bc55 *\Contents\SharedSupport\BaseSystem.dmg
0004 6ffeea24777521c2bd0308f1f2f94579f04a1b14 *\Contents\SharedSupport\InstallESDDmg.pkg
0004 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist

The info.plist are all the same which means the specific version and build for all of them are the same.

**Comment by Setaran** [comment]
How should I download a full installer 4.x GB of High Sierra that won't cause me this much headache? lol

**Comment by Setaran** [comment]
Because I've heard a particular Mac OS downloads HS's full installer. Anyone knows which it is?

**Comment by ws4liu** [comment]
cf7c315c0ee033697d8648e6d87825061b3a9cb5 *\Contents\SharedSupport\BaseSystem.dmg
9082686f9caabe2ffe73a8b2d3883dd6fb0fd974 *\Contents\SharedSupport\InstallESD.dmg
7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist
macOS High Sierra 10.13.6 17G66

**Comment by dcamp314** [comment]
> cf7c315c0ee033697d8648e6d87825061b3a9cb5 *\Contents\SharedSupport\BaseSystem.dmg
> 9082686f9caabe2ffe73a8b2d3883dd6fb0fd974 *\Contents\SharedSupport\InstallESD.dmg
> 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1 *\Contents\Info.plist
> macOS High Sierra 10.13.6 **17G66**

@ws4liu, hmmm… my High Sierra 13.6.02 installer with the same digests as you reported is labelled **17G61** (instead of 17G66):

`$ shasum Install\ macOS\ High\ Sierra.app/Contents/SharedSupport/{Base,Install}*.dmg Install\ macOS\ High\ Sierra.app/Contents/*.plist`
```
cf7c315c0ee033697d8648e6d87825061b3a9cb5  Install macOS High Sierra.app/Contents/SharedSupport/BaseSystem.dmg
9082686f9caabe2ffe73a8b2d3883dd6fb0fd974  Install macOS High Sierra.app/Contents/SharedSupport/InstallESD.dmg
7a81b0b25a44c48bf77fbf88a14dab7d95f654d1  Install macOS High Sierra.app/Contents/Info.plist
328a3af9592d038af0c1ed477439863c5f12e9e9  Install macOS High Sierra.app/Contents/version.plist
```
`$ plutil -p Install\ macOS\ High\ Sierra.app/Contents/Info.plist  # Note: 7a81b0b25a44c48bf77fbf88a14dab7d95f654d1`
```
{
  "Application-Group" => "AirPort"
  "BuildMachineOSBuild" => "16B2657"
  "CFBundleDevelopmentRegion" => "English"
  "CFBundleDisplayName" => "Install macOS High Sierra"
  "CFBundleExecutable" => "InstallAssistant_springboard"
  "CFBundleGetInfoString" => "Install macOS High Sierra, Copyright © 2007-2018 Apple Inc. All rights reserved."
  "CFBundleIconFile" => "InstallAssistant"
  "CFBundleIdentifier" => "com.apple.InstallAssistant.HighSierra"
  "CFBundleInfoDictionaryVersion" => "6.0"
  "CFBundleName" => "Install mac OS"
  "CFBundlePackageType" => "APPL"
  "CFBundleShortVersionString" => "13.6.02"
  "CFBundleSignature" => "????"
  "CFBundleSupportedPlatforms" => [
    0 => "MacOSX"
  ]
  "CFBundleURLTypes" => [
    0 => {
      "CFBundleURLName" => "Open Install OS X URL"
      "CFBundleURLSchemes" => [
        0 => "x-install-osx-assistant"
      ]
    }
  ]
  "CFBundleVersion" => "13602"
  "DTCompiler" => "com.apple.compilers.llvm.clang.1_0"
  "DTPlatformBuild" => "9P107g"
  "DTPlatformVersion" => "GM"
  "DTSDKBuild" => "17G61"
  "DTSDKName" => "macosx10.13internal"
  "DTXcode" => "0930"
  "DTXcodeBuild" => "9P107g"
  "LSApplicationCategoryType" => "public.app-category.utilities"
  "LSArchitecturePriority" => [
    0 => "x86_64"
    1 => "i386"
    2 => "ppc"
  ]
  "LSHasLocalizedDisplayName" => 1
  "LSMinimumSystemVersion" => "10.8"
  "NSMainNibFile" => "MainMenu"
  "NSPrincipalClass" => "NSApplication"
  "NSSupportsAutomaticGraphicsSwitching" => 1
  "ProductPageIconFile" => "ProductPageIcon.icns"
}
```
`$ plutil -p Install\ macOS\ High\ Sierra.app/Contents/version.plist`
```
{
  "BuildAliasOf" => "InstallAssistant"
  "BuildVersion" => "331"
  "CFBundleShortVersionString" => "13.6.02"
  "CFBundleVersion" => "13602"
  "ProjectName" => "InstallAssistant"
  "SourceVersion" => "1129005000000000"
}
```
FYI, the plist files are dated 2018-06-28.

**Comment by 1alessandro1** [comment]
@markmentovai @notpeter can we add the 17G66 hashes to the `readme.md`?

Seems like from the catalogue this is the only downloadable version:

![image](https://user-images.githubusercontent.com/46293832/105693947-a6529200-5f00-11eb-9aa5-e16c846ac03a.png)


if you want to test yourself:

```
curl -O https://raw.githubusercontent.com/munki/macadmin-scripts/main/installinstallmacos.py && sudo /usr/bin/python installinstallmacos.py
```

If necessary I can double check the SHA-1 and SHA-256 which were mentioned in this issue and maybe add them with a PR

**Comment by 1alessandro1** [comment]
Closing as already fixed, 17G66 taken from apple's catalogue is present in the README
