### ISSUE TITLE
SHA1 should not be used - it's compromised; you should list commands for running SHA256 and list SHA256 values

### ISSUE THREAD

**Issue by CalculonPrime** [notpeter/apple-installer-checksums#66]
Listing SHA1 values gives visitors a false sense of security since SHA1 is compromised.

https://fossbytes.com/google-broke-sha-1-encryption-hash/
https://medium.com/@computersys11/google-kills-sha-1-with-successful-collision-attack-fa327711cb8c
https://www.computerworld.com/article/3173616/the-sha1-hash-function-is-now-completely-unsafe.html

Looking forward to all references to SHA1 disappearing.

**Comment by 1alessandro1** [comment]
@CalculonPrime visitors can check the raw readme.md to find the corresponding SHA-256 hashes of their images. 

Can this be closed?
