### ISSUE TITLE
Please update the rest of the installers affected by the certificate expiration

### ISSUE THREAD

**Issue by Juesto** [notpeter/apple-installer-checksums#68]
as you said in your comment in #65 that's indeed correct but it also applies for Yosemite-high sierra not just mojave.

**Comment by KvL-KvL** [comment]
As of today, in fact, SHA1 hash of macOS High Sierra 10.13.6 seem to be:

- BaseSystem.dmg cf7c315c0ee033697d8648e6d87825061b3a9cb5

- InstallESD.dmg 9082686f9caabe2ffe73a8b2d3883dd6fb0fd974

Thanks,

K.

**Comment by 1alessandro1** [comment]
The latest official installers for old versions of macOS can be found here:

https://support.apple.com/en-us/HT211683

In particular:

- [macOS Sierra](http://updates-http.cdn-apple.com/2019/cert/061-39476-20191023-48f365f4-0015-4c41-9f44-39d3d2aca067/InstallOS.dmg)
- [OS X El Capitan](http://updates-http.cdn-apple.com/2019/cert/061-41424-20191024-218af9ec-cf50-4516-9011-228c78eda3d2/InstallMacOSX.dmg)
- [OS X Yosemite](http://updates-http.cdn-apple.com/2019/cert/061-41343-20191023-02465f92-3ab5-4c92-bfe2-b725447a070d/InstallMacOSX.dmg)


All these hashes are present in the readme already
