### ISSUE TITLE
Some older Xcode archives have incorrect hashes related to certificate resigning

### ISSUE THREAD

**Issue by sleeve** [notpeter/apple-installer-checksums#82]
As it was mentioned in #65 -- some older macOS installer packages/archives include an expired certificate and no longer extract/install properly. Unfortunately this also affects some of the older Xcode archives.

https://medium.com/@hammen/the-apple-packagepocalypse-2019-edition-6e2d4bc0aa90

When trying to open a previously downloaded Xcode archive with an expired certificate an error is displayed with the message: `The archive "Xcode.xip" does not come from Apple.`
![Screen Shot 2020-05-15 at 11 38 40 AM](https://user-images.githubusercontent.com/499487/82085835-74670b80-96a2-11ea-99ad-a42c0a54adba.png)

One workaround that seems to work for some people is to manually change your system time back to September 2019 and then attempt to extract the archive.

https://forums.developer.apple.com/thread/125108
https://stackoverflow.com/questions/59036191/xcode-xip-the-archive-does-not-come-from-apple

Apple started replacing the affected Xcode archives between October-December 2019 but kept the same filename/download URLs as the original (now non-funtioning) versions. So now, pretty much **half of the hashes for older Xcode versions do not match** when you download the currently hosted file.

I'm planning on updating the hashes for all the affected releases but I'm not entirely sure if I should keep both the old and new hashes for a specific release or just display the new hash for the working version? @notpeter Do you have a preference?

**Comment by sartbimpson** [comment]
I would suggest that the old and new hashes are both retained for archival purposes

**Comment by notpeter** [comment]
A year late, but would prefer to include all valid hashes especially when released under the same filename (re-signing).
PR's welcome!
