### ISSUE TITLE
Regarding How Do I Help

### ISSUE THREAD

**Issue by dodekeract** [notpeter/apple-installer-checksums#9]
I think it'd actually be helpful to verify the checksums too, so I'd recommend adding a phrase saying that verifying them is also good.

Reasoning: Somebody may troll or change checksums with malicious intent, if **you** don't have the original file, there is no way for you to be sure they're not lying.

Thanks for this project though, it's really nice to know I got the correct file.

**Comment by notpeter** [comment]
Yep, 

I've verified checksums in all the PRs I've gotten so far for new releases, but if it was on something older I'm not sure what the best procedure would be for me to "verify" a checksum for a file I don't actually possess.

I guess I'd prefer to err on the side of caution as an unvalidated checksum is far worse than an incomplete list. Generally though, I would be weary to accept a PR from a GitHub account with little reputation/history, but open to suggestions on how to 'verify' ISOs no longer generally available.

**Comment by dodekeract** [comment]
Maybe googling the checksum can be helpful in this case.

**Comment by dodekeract** [comment]
I think we can close this. There doesn't seem to be a good solution.

Only thing we can do is include a "source", which lists all users that confirmed the checksum.
