### ISSUE TITLE
Add macOS Catalina 10.15.6 (19G73) hashes

### ISSUE THREAD

**Issue by 1alessandro1** [notpeter/apple-installer-checksums#91]
SHA-1 = b3a620e7df4b0d8a193f7d85cdd28bac92c907fa BaseSystem.dmg
SHA-1 = 77038bc8ad58139d10a6eed9b09e56bf3eb89642 InstallESD.dmg
SHA-256 = 090c4825b6de79bf92cce70d110cfc12f6b6f90b3c54dc05f6ae5bfa3ce910ae BaseSystem.dmg
SHA-256 = f77b8ecb971b6697e19a04b734124381e20269984c73c4054cdfc9c728f580a0 InstallESD.dmg

**Comment by superlex** [comment]
Thanks @1alessandro1 , confirmed.

**Comment by markmentovai** [comment]
Fixed by e330107b4767, thanks!
